name: kdtGradlePipeline

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: updateJavaSDK
        uses: actions/setup-java@v3
        with: 
          java-version: '17'
          distribution: 'temurin'
          cache: gradle
      
      - name: Set-up-Gradle-Wrapper&osv-scanner
        run: |
          sudo apt install golang-go
          go version
          chmod +x ./gradlew
          go install github.com/google/osv-scanner/cmd/osv-scanner@v1

      - name: Setup KDT
        run: |
          curl -sSL https://cli.kondukto.io | sh
          echo "KONDUKTO_HOST=${{ secrets.KONDUKTO_HOST }}" >> $GITHUB_ENV
          echo "KONDUKTO_TOKEN=${{ secrets.KONDUKTO_TOKEN }}" >> $GITHUB_ENV
      - name: GenerateSBOM-with-cycloneDX-Plugin
        run: |
          gradle cyclonedxBom
      - name: scan-SBOM-with-osv-scanner
        run: |
          osv-scanner -S bom.json --json --output sbom-scan.json
      - name: import-generated-SBOM
        run: |
          kdt sbom import -p kotlin-petclinic -b main -f bom.json
      - name: import-SBOM-Scan-with-osvscannersca
        run: |
          kdt scan -p kotlin-petclinic -b main -t osvscannersca -f sbom-scan.json
         
      
      
