name: kdtGradlePipeline

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: updateJavaSDK
        uses: actions/setup-java@v3
        with: 
          java-version: '17'
          distribution: 'temurin'
          cache: gradle
      
      - name: Set up Gradle Wrapper& install Syft
        run: |
          chmod +x ./gradlew
          curl -sSfL https://raw.githubusercontent.com/anchore/syft/main/install.sh | sh -s -- -b /usr/local/bin
      - name: Setup KDT
        run: |
          curl -sSL https://cli.kondukto.io | sh
          echo "KONDUKTO_HOST=${{ secrets.KONDUKTO_HOST }}" >> $GITHUB_ENV
          echo "KONDUKTO_TOKEN=${{ secrets.KONDUKTO_TOKEN }}" >> $GITHUB_ENV

      - name: Build-Gradle & GenerateSBOM-withSyft
        run: |
          ./gradlew build
          syft ../sbom-gradle-cyclonedx-pipeline-scan -o cyclonedx-json --file kotlin-cyclonedx.json
      - name: import-SBOM&osv-scan
        run: |
          
          kdt scan 
          -p kotlin-petclinic 
          -t osvscannersca 
          -b main 
          -f osv-scanner-result.json
          kdt sbom import 
          -p kotlin-petclinic 
          -b main 
          -f kotlin-cyclonedx.json
      
      
