name: kdtGradlePipeline

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: updateJavaSDK
        uses: actions/setup-java@v3
        with: 
          java-version: '17'
          distribution: 'temurin'
          cache: gradle
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.21'
      - name: osv-scanner
        run: |
          wget https://github.com/google/osv-scanner/releases/download/v1.5.0/osv-scanner_1.5.0_linux_amd64 -O osv-scanner  && chmod +x osv-scanner
          ls
          chmod +x ./gradlew
          chmod +x osv-scanner
      - name: Setup KDT
        run: |
          curl -sSL https://cli.kondukto.io | sh
          echo "KONDUKTO_HOST=${{ secrets.KONDUKTO_HOST }}" >> $GITHUB_ENV
          echo "KONDUKTO_TOKEN=${{ secrets.KONDUKTO_TOKEN }}" >> $GITHUB_ENV
      - name: GenerateSBOM-with-cycloneDX-Plugin
        run: |
          gradle cyclonedxBom
      - name: scan-SBOM-with-osv-scanner
        run: |
          ./osv-scanner -S bom.json --json --output sbom-osv-scan.json && ls
          ls -la
          tail sbom-osv-scan.json
      - name: import-generated-SBOM
        run: |
          kdt sbom import -p kotlin-petclinic -b main -f bom.json
      - name: import-SBOM-Scan-with-osvscannersca
        run: |
          tail sbom-osv-scan.json
          kdt scan -p kotlin-petclinic -b main -t osvscannersca -f sbom-osv-scan.json
          echo $(./osv-scanner -S bom.json --json --output sbom-osv-scan.json && ls)
          
      
      
