name: kdtGradlePipeline

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: updateJavaSDK
        uses: actions/setup-java@v3
        with: 
          java-version: '17'
          distribution: 'temurin'
          cache: gradle
      
      - name: Set up Gradle Wrapper& install Syft
        run: |
          chmod +x ./gradlew
      - name: Setup KDT
        run: |
          curl -sSL https://cli.kondukto.io | sh
          echo "KONDUKTO_HOST=${{ secrets.KONDUKTO_HOST }}" >> $GITHUB_ENV
          echo "KONDUKTO_TOKEN=${{ secrets.KONDUKTO_TOKEN }}" >> $GITHUB_ENV

      - name: Build-Gradle & GenerateSBOMwithcycloneDX Plugin
        run: |
          gradle cyclonedxBom
          ls 
          kdt sbom import -p kotlin-petclinic -b main -f bom.json
      - name: osv-scan&imported-SBOM
        run: |
          kdt scan -p kotlin-petclinic -b main -t osvscannersca 
          kdt scan -p kotlin-petclinic -t osvscannersca -b main -f osv-scanner-result.json
         
      
      
