name: kdtGradlePipeline

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: updateJavaSDK
        uses: actions/setup-java@v3
        with: 
          java-version: '17'
          distribution: 'temurin'
          cache: gradle
      - name: update-software
        run: |
          go version
          sudo apt update
          sudo apt install software-properties-common
          sudo add-apt-repository ppa:longsleep/golang-backports
          sudo apt update
          sudo apt install golang-go
          go version
      - name: osv-scanner
        run: |
          chmod +x ./gradlew
          echo " here ls command "
          ls
          echo " here go install osvscanner command "
          go install github.com/google/osv-scanner/cmd/osv-scanner@v1
          go install github.com/google/osv-scanner@latest
          if [ -f "$(go env GOPATH)/bin/osv-scanner" ]; then
            echo "osv-scanner installed successfully."
          else
            echo "osv-scanner installation failed."
            exit 1
          fi
          echo "$(go env GOPATH)/bin" >> $GITHUB_PATH
          osv-scanner --help
          git clone https://github.com/google/osv-scanner.git
          ls
          ./osv-scanner/scripts/build.sh
          ./osv-scanner--help


      - name: Setup KDT
        run: |
          curl -sSL https://cli.kondukto.io | sh
          echo "KONDUKTO_HOST=${{ secrets.KONDUKTO_HOST }}" >> $GITHUB_ENV
          echo "KONDUKTO_TOKEN=${{ secrets.KONDUKTO_TOKEN }}" >> $GITHUB_ENV
      - name: GenerateSBOM-with-cycloneDX-Plugin
        run: |
          gradle cyclonedxBom
      - name: scan-SBOM-with-osv-scanner
        run: |
          osv-scanner -S bom.json --json --output sbom-scan.json
      - name: import-generated-SBOM
        run: |
          kdt sbom import -p kotlin-petclinic -b main -f bom.json
      - name: import-SBOM-Scan-with-osvscannersca
        run: |
          kdt scan -p kotlin-petclinic -b main -t osvscannersca -f sbom-scan.json
         
      
      
